### ISSUE TITLE
Eisen trasformation 

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [eisen-ai/eisen-core#3]
I would like to save my input  after normalization and resize as numpy. What is the procedure?
thanks so much!!

**Comment by eisen-ai** [comment]
I don't know if I understand correctly...  you would like to dump your data to disk right after it gets transformed (pre-processed).

You can do that by creating a new transformation:

```
import uuid

class DumpAsNumpy:
    def __init__(self, fields, path):
        self.fields = fields
        self.path = path

   def __call__(self, data):
       for field in self.fields:
           f_name = str(uuid.uuid4())
           numpy.save(data[field], os.path.join(self.path, f_name)

           data[self.field + '_file'] = f_name

    return data
```

**Comment by eisen-ai** [comment]
Of course this additional transform that dumps data to disk might not have exactly this form. But one instance of this object could be part of the transform chain and therefore save copied of data on the disk.

**Comment by bioinfo-dirty-jobs** [comment]
thanks so much!! I make some confusion I'm interested to use the data normalizated from you tool for extract radiomics. So, I wan to integrate  deep learning model with radiomics. I just wondering how to save the data after trasformation on nifty format.

**Comment by eisen-ai** [comment]
you would need to write one more transformation which DumpsAsNifti. Right now DumpAsNumpy will dump files into the ./tmp folder (not into /tmp, because you didn't specify '/tmp' but 'tmp/' instead) in numpy format.
