### ISSUE TITLE
tensorboard summary confusion matrix looks bad for binary labels

### ISSUE THREAD

**Issue by dasturge** [eisen-ai/eisen-core#6]
scaling is pretty poor in this case, upper left box number is not rendering.

![individualImage](https://user-images.githubusercontent.com/18649005/80755002-de998100-8ae4-11ea-9c9e-2a3463e2a33f.png)

**Comment by eisen-ai** [comment]
does #5 fix this issue as well?

**Comment by dasturge** [comment]
@eisen-ai no, #5 just keeps it from crashing for binary labels.

There's two issues with the image I think:  

1. The numbers are normalized by true label, while the visual color scale is normalized by global count, so the text appears white over a white-ish tile for this heavily imbalanced class example.  The text should be white/black based on the global ratio.

2. The figure size set is probably good for many classes, but poor for this few and should maybe be a bit larger.  Probably there should just be a minimum figure size and it should grow if the user has a large number of classes.

**Comment by eisen-ai** [comment]
should be resolved in ef805bb
